env:
  browser: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
plugins:
  - '@typescript-eslint'
  - 'react'
  - 'react-hooks'
rules:
  'dot-notation': off
  'prefer-promise-reject-errors': off
  'no-prototype-builtins': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-this-alias': off
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-non-null-assertion': off
  'react/jsx-wrap-multilines': off
  'react/jsx-no-target-blank': off
  'react/prop-types': off
  'react/jsx-no-literals': warn
  'react/jsx-no-useless-fragment': off
  'react-hooks/rules-of-hooks': error
  'react-hooks/exhaustive-deps': off
  'no-use-before-define': off
  'no-return-assign': off
  'no-unused-expressions': off
  'no-sequences': off
  'camelcase': off
  'plugin/no-low-performance-animation-properties': 0
  '@typescript-eslint/ban-ts-comment': off
  quotes:
    - warn
    - single
    - avoidEscape: false
  semi:
    - error
    - always
