nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  "@inkline/nuxt@*":
    peerDependencies:
      webpack: "*"
  "@nuxt/typescript-build@*":
    peerDependencies:
      webpack: "*"
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "web3-provider-engine@*":
    peerDependencies:
      "@babel/core": "*"
  "@portis/web3@*":
    peerDependencies:
      "@babel/core": "*"
  "@nuxtjs/eslint-config-typescript@*":
    peerDependencies:
      eslint: "*"


yarnPath: .yarn/releases/yarn-berry.cjs
