nodeLinker: node-modules

packageExtensions:
  "@inkline/nuxt@*":
    peerDependencies:
      "@inkline/inkline": "*"
      vue: "*"
      webpack: "*"
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "@nuxt/typescript-build@*":
    peerDependencies:
      webpack: "*"
  "@nuxtjs/axios@*":
    peerDependencies:
      axios: "*"
  "@nuxtjs/eslint-config-typescript@*":
    peerDependencies:
      eslint: "*"
  "@portis/web3@*":
    peerDependencies:
      "@babel/core": "*"
  jest@*:
    peerDependencies:
      "@babel/core": "*"
  babel-core@*:
    peerDependencies:
      "@babel/core": "*"
  web3-provider-engine@*:
    peerDependencies:
      "@babel/core": "*"
  zksync@*:
    peerDependencies:
      "@ethersproject/logger": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
