nodeLinker: node-modules

packageExtensions:
  "@nuxt/typescript-build@*":
    peerDependencies:
      webpack: "*"
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "web3-provider-engine@*":
    peerDependencies:
      "@babel/core": "*"
  "@portis/web3@*":
    peerDependencies:
      "@babel/core": "*"
  "@nuxtjs/eslint-config-typescript@*":
    peerDependencies:
      eslint: "*"
  "cypress-nuxt@*":
    peerDependencies:
      webpack: "*"
      "@cypress/webpack-preprocessor": "*"
  "@cypress/vue@*":
    peerDependencies:
      "@vue/test-utils": "*"
      vue-template-compiler: "*"
      vue: "*"
  "typed-vuex@*":
    peerDependencies:
      "vuex": "*"
  "@nuxtjs/axios@*":
    peerDependencies:
      "axios": "*"
  "zksync@*":
    peerDependencies:
      "@ethersproject/logger": "*"
  "@inkline/nuxt@*":
    peerDependencies:
      vue: "*"
      webpack: "*"
      "@inkline/inkline": "*"



yarnPath: ".yarn/releases/yarn-rc.js"
