name: Build and Publish Zksync Wallet (to Firebase)

on:
  push:
    tags:
      - '*-beta'
    branches:
      - develop

  # pull_request:
  #   types: [closed]
  #   branches:
  #     - development
  #

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - chain: mainnet
          - chain: rinkeby
          - chain: ropsten

    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v2

      - name: Select Firebase project and hosting
        run: |
          # hostings are in zksync-demo projects
          echo "FIREBASE_PROJECT=zksync-demo" >> $GITHUB_ENV

          if [[ "${{ env.CI_REF_NAME }}" =~ ^feature/.*-beta ]]; then
            echo "FIREBASE_HOSTING=${{ matrix.chain }}-beta" >> $GITHUB_ENV
          elif [[ "${{ env.CI_REF_NAME }}" =~ ^develop$ ]]; then
            echo "FIREBASE_HOSTING=${{ matrix.chain }}-stage" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Populate webpack env file
        run: |
          cat environments/.env.${{ matrix.chain }} >> environments/.env

      - name: Build static site and publish to Firebase
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: static-image
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64
          file: ./Dockerfile.build-and-publish
          build-args: |
            FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN}}
            FIREBASE_PROJECT=${{ env.FIREBASE_PROJECT }}
            FIREBASE_HOSTING=${{ env.FIREBASE_HOSTING }}
